load_project: ''
photo_path: /ofo-share/ofo-itd-crossmapping_data/drone-imagery-raw/20230707-0158
multispectral: no
output_path: /ofo-share/ofo-itd-crossmapping_data/photogrammetry/outputs
project_path: /ofo-share/ofo-itd-crossmapping_data/photogrammetry/projects
run_name: ''
project_crs: EPSG::3310
subdivide_task: yes
use_cuda: yes
gpu_multiplier: 2
use_rtk: no
fix_accuracy: 3
nofix_accuracy: 25
addGCPs:
  enabled: no
  gcp_crs: EPSG::26910
  marker_location_accuracy: 0.1
  marker_projection_accuracy: 8
  optimize_w_gcps_only: yes
calibrateReflectance:
  enabled: no
  panel_filename: RP04-1923118-OB.csv
  use_reflectance_panels: yes
  use_sun_sensor: yes
alignPhotos:
  enabled: yes
  downscale: 4
  adaptive_fitting: yes
  keep_keypoints: yes
  reset_alignment: no
  generic_preselection: yes
  reference_preselection: yes
  reference_preselection_mode: Metashape.ReferencePreselectionSource
  export: yes
filterPointsUSGS:
  enabled: yes
  rec_thresh_percent: 20
  rec_thresh_absolute: 15
  proj_thresh_percent: 30
  proj_thresh_absolute: 2
  reproj_thresh_percent: 5
  reproj_thresh_absolute: 0.3
optimizeCameras:
  enabled: yes
  adaptive_fitting: yes
  export: yes
buildDepthMaps:
  enabled: yes
  downscale: 4
  filter_mode: Metashape.ModerateFiltering
  reuse_depth: no
  max_neighbors: 100
buildPointCloud:
  enabled: yes
  keep_depth: yes
  max_neighbors: 100
  classify_ground_points: yes
  export: no
  classes: ALL
classifyGroundPoints:
  max_angle: 15.0
  max_distance: 1.0
  cell_size: 50.0
buildModel:
  enabled: no
  face_count: Metashape.MediumFaceCount
  face_count_custom: 100000
  export_local: yes
  export_transform: no
  export_georeferenced: yes
  export_extension: ply
buildDem:
  enabled: yes
  classify_ground_points: no
  surface:
  - DTM-ptcloud
  - DSM-ptcloud
  - DSM-mesh
  resolution: 0
  export: yes
  tiff_big: yes
  tiff_tiled: no
  nodata: -32767
  tiff_overviews: yes
buildOrthomosaic:
  enabled: no
  surface:
  - DTM-ptcloud
  - DSM-ptcloud
  - DSM-mesh
  - Mesh
  blending: Metashape.MosaicBlending
  fill_holes: yes
  refine_seamlines: yes
  export: yes
  tiff_big: yes
  tiff_tiled: yes
  nodata: -32767
  tiff_overviews: yes
