# Purpose: set global constants for the imagery data processing pipeline. They mostly consist of
# paths to files/dirs for input/output data.

# nolint start

library(tidyverse)
library(unixtools) # To set tempdir during session

# What is the padding width for the dataset ID in the folder names of the imagery folders to be ingested? (New format) This is used to
# force the Baserow dataset ID column to conform to the image folder names, so this should reflect
# the padding used when naming the image folders in the 1_manually-cleaned folder.
FOLDER_DATASET_ID_PADDING = 6


IMAGE_MERGE_DISTANCE = 50
# NRS datasets need a larger merge distance because some datasets used very low overlap
IMAGE_MERGE_DISTANCE_NRS_OVERRIDE = 100
NRS_PROJECT_ID = "20200211-0008"

# For example image selection & image set zipping
N_EXAMPLE_IMAGES = 4
THUMBNAIL_SIZE = "800"
SKIP_EXISTING = FALSE # Skip processing for missions that already have all outputs


# Base path for project data
# BASE_DATA_PATH = "/ofo-share/project-data/catalog-data-prep/"
BASE_DATA_PATH = "/z_OLD_ofo-share/ARCHIVED__SEE_README/catalog-data-prep/"

PROJECT_TO_PROCESS_RAW_IMAGERY_METADATA_FILEPATH = file.path(BASE_DATA_PATH, "00_missions-to-process/01_raw-imagery-meatadata-prep/project-to-process.txt")
PROJECT_NAME_TO_PROCESS_RAW_IMAGERY_METADATA = tryCatch(
  read_lines(PROJECT_TO_PROCESS_RAW_IMAGERY_METADATA_FILEPATH),
  error = function(e) {
    warning("Could not read file: ", PROJECT_TO_PROCESS_RAW_IMAGERY_METADATA_FILEPATH, "\n", e$message)
    character(0)
  }
)
MISSIONS_TO_PROCESS_RAW_IMAGERY_METADATA_LIST_PATH = file.path(BASE_DATA_PATH, "00_missions-to-process/01_raw-imagery-meatadata-prep/missions-to-process.csv")

RAW_IMAGERY_INGESTION_PATH = file.path(BASE_DATA_PATH, "01_raw-imagery-ingestion")

CONTRIBUTED_IMAGERY_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "1_manually-cleaned")
RAW_EXIF_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/1_reconciling-contributions/1_raw-exif/")

CONTRIBUTED_METADATA_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-inputs/baserow-snapshots")

# List of mission IDs from NRS project (generated by one-off script, used for merge distance override)
NRS_MISSIONS_LIST_FILEPATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-inputs/project-configs/nrs-mission-ids.csv")
NRS_MISSION_IDS = tryCatch(
  read_csv(NRS_MISSIONS_LIST_FILEPATH, show_col_types = FALSE)$mission_id,
  error = function(e) {
    warning("Could not read NRS missions list: ", NRS_MISSIONS_LIST_FILEPATH, "\n", e$message)
    character(0)
  }
)

CONTRIBUTED_TO_SORTED_MISSION_ID_CROSSWALK_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/1_reconciling-contributions/3_contributed-to-sorted-id-crosswalk/")

IMAGE_EXIF_W_SORTING_PLAN_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/1_reconciling-contributions/2_exif-w-sorting-plan/")

# Should be "conributed"
EXTRACTED_METADATA_PER_MISSION_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/2_pre-curation-intermediate/1_contributed-metadata-per-mission/")
EXTRACTED_METADATA_PER_SUB_MISSION_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/2_pre-curation-intermediate/2_contributed-metadata-per-sub-mission/")

PARSED_EXIF_METADATA_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/2_pre-curation-intermediate/4_parsed-exif")
DUPLICATE_IMAGES_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/2_pre-curation-intermediate/5_duplicate-images")
PARSED_EXIF_DEDUPED_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/2_pre-curation-intermediate/6_parsed-exif-duplicates-removed")

PARSED_EXIF_FOR_RETAINED_IMAGES_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/3_pre-curation-final/3_parsed-exif-per-image")
DERIVED_METADATA_PER_MISSION_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/2_pre-curation-intermediate/7_derived-metadata-per-mission")
DERIVED_METADATA_PER_SUB_MISSION_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/2_pre-curation-intermediate/8_derived-metadata-per-sub-mission")

FULL_METADATA_PER_MISSION_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/3_pre-curation-final/1_full-metadata-per-mission/")
FULL_METADATA_PER_SUB_MISSION_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/3_pre-curation-final/2_full-metadata-per-sub-mission/")

# The following file should not be assumed to be there, since we are not necessarily keeping all
# mission data combined locally, and it should not be assumed to contain every mission, but this is where the file will be if it has been created
FULL_METADATA_PER_MISSION_COMBINED_FILEPATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/3_pre-curation-final/ofo-all-missions-metadata.gpkg")
FULL_METADATA_PER_IMAGE_COMBINED_FILEPATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/3_pre-curation-final/ofo-all-images-metadata.gpkg")

# Catalog-wide merged duplicate images log (combined from all per-project logs)
CATALOG_DUPLICATE_IMAGES_LOG_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/3_pre-curation-final/catalog-duplicate-images-log.csv")

CURATION_NOTES_FILEPATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-inputs/curation-records/imagery-curation-notes_v4.csv")
FORMERLY_CURATED_IMAGE_METADATA = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-inputs/curation-records/formerly-curated-image-metadata_20250419.gpkg")
FORMERLY_CURATED_MISSION_LIST = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-inputs/curation-records/formerly-curated-mission-list_20250419.csv")

# Missing constant (used by scripts but not defined)
SORTED_IMAGERY_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "2_sorted")

# Post-curation intermediate paths (mirror pre-curation structure)
POST_CURATION_INTERMEDIATE_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/5_post-curation-intermediate")

POST_CURATION_INTERMEDIATE_PARSED_EXIF_PATH = file.path(POST_CURATION_INTERMEDIATE_PATH, "1_parsed-exif-per-image")
POST_CURATION_DERIVED_METADATA_PER_MISSION_PATH = file.path(POST_CURATION_INTERMEDIATE_PATH, "2_derived-metadata-per-mission")
POST_CURATION_DERIVED_METADATA_PER_SUB_MISSION_PATH = file.path(POST_CURATION_INTERMEDIATE_PATH, "3_derived-metadata-per-sub-mission")

# Post-curation final paths
POST_CURATION_FINAL_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "metadata-outputs/6_post-curation-final")

POST_CURATION_PARSED_EXIF_FOR_RETAINED_IMAGES_PATH = file.path(POST_CURATION_FINAL_PATH, "1_parsed-exif-per-image")
POST_CURATION_FULL_METADATA_PER_MISSION_PATH = file.path(POST_CURATION_FINAL_PATH, "2_full-metadata-per-mission")
POST_CURATION_FULL_METADATA_PER_SUB_MISSION_PATH = file.path(POST_CURATION_FINAL_PATH, "3_full-metadata-per-sub-mission")

# Combined post-curation metadata files
POST_CURATION_FULL_METADATA_PER_MISSION_COMBINED_FILEPATH = file.path(POST_CURATION_FINAL_PATH, "ofo-all-missions-metadata-curated.gpkg")
POST_CURATION_FULL_METADATA_PER_IMAGE_COMBINED_FILEPATH = file.path(POST_CURATION_FINAL_PATH, "ofo-all-images-metadata-curated.gpkg")

PROJECT_TO_PROCESS_RAW_IMAGERY_FILES_FILEPATH = file.path(BASE_DATA_PATH, "00_missions-to-process/02_raw-imagery-file-prep/projects-to-process.txt")
PROJECT_NAMES_TO_PROCESS_RAW_IMAGERY_FILES = tryCatch(
  read_lines(PROJECT_TO_PROCESS_RAW_IMAGERY_FILES_FILEPATH),
  error = function(e) {
    warning("Could not read file: ", PROJECT_TO_PROCESS_RAW_IMAGERY_FILES_FILEPATH, "\n", e$message)
    character(0)
  }
)
# Exclude "commented out" project names
PROJECT_NAMES_TO_PROCESS_RAW_IMAGERY_FILES = PROJECT_NAMES_TO_PROCESS_RAW_IMAGERY_FILES[!grepl("^#", PROJECT_NAMES_TO_PROCESS_RAW_IMAGERY_FILES)]

MISSIONS_TO_PROCESS_RAW_IMAGERY_FILES_LIST_PATH = file.path(BASE_DATA_PATH, "00_missions-to-process/02_raw-imagery-file-prep/missions-to-process.csv")

IMAGERY_ZIP_AND_EXAMPLES_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "4_raw-imagery-zip-and-examples")

IN_PROCESS_PATH = "/ofo-share/tmp/raw-imagery-publish-prep-progress-tracking/"

UPLOAD_STAGING_DIR_PATH = file.path(RAW_IMAGERY_INGESTION_PATH, "9_temp-upload-staging")

# Name of configured rclone remote for object storage
RCLONE_REMOTE = "js2s3"
REMOTE_MISSIONS_DIR = "/ofo-public/drone/missions_03/"
REMOTE_PHOTOGRAMMETRY_DIR = "/ofo-internal/photogrammetry-outputs/"

UPLOAD_ERROR_LOG = file.path(RAW_IMAGERY_INGESTION_PATH, "temp/cyverse-upload-log.txt")


PROJECTS_TO_PROCESS_PHOTOGRAMMETRY_FILEPATH = file.path(BASE_DATA_PATH, "00_missions-to-process/03_photogrammetry/projects-to-process.txt")
PROJECT_NAMES_TO_PROCESS_PHOTOGRAMMETRY = tryCatch(
  read_lines(PROJECTS_TO_PROCESS_PHOTOGRAMMETRY_FILEPATH),
  error = function(e) {
    warning("Could not read file: ", PROJECTS_TO_PROCESS_PHOTOGRAMMETRY_FILEPATH, "\n", e$message)
    character(0)
  }
)
# Exclude "commented out" project names
PROJECT_NAMES_TO_PROCESS_PHOTOGRAMMETRY = PROJECT_NAMES_TO_PROCESS_PHOTOGRAMMETRY[!grepl("^#", PROJECT_NAMES_TO_PROCESS_PHOTOGRAMMETRY)]

MISSIONS_TO_PROCESS_PHOTOGRAMMETRY_LIST_PATH = file.path(BASE_DATA_PATH, "00_missions-to-process/03_photogrammetry/missions-to-process.csv")
MISSIONS_TO_PROCESS_PHOTOGRAMMETRY_PATH = file.path(BASE_DATA_PATH, "00_missions-to-process/03_photogrammetry")




# OFO_R_REPO_PATH = "/ofo-share/repos-derek/ofo-r"

AUTOMATE_METASHAPE_PATH = "/ofo-share/repos-derek/automate-metashape"

PHOTOGRAMMETRY_DIR = file.path(BASE_DATA_PATH, "02_photogrammetry")

# All of these are relative to PHOTOGRAMMETRY_DIR:
BASE_METASHAPE_CONFIG_SUBPATH = "01_base-metashape-config"
DOWNLOADED_IMAGERY_ZIP_SUBDIR = "02_downloaded-imagery-zip"
INPUT_IMAGES_SUBDIR = "03_input-images"
DERIVED_METASHAPE_CONFIG_SUBDIR = "04_derived-metashape-configs"
METASHAPE_PROJECT_SUBDIR = "05_photogrammetry-projects"
METASHAPE_OUTPUT_SUBDIR = "06_photogrammetry-outputs"
# After the Metashape processing is done, the outputs are uploaded, deleted from the above
# folder, then downloaded to the folder below
METASHAPE_OUTPUT_DOWNLOADED_SUBDIR = "06_photogrammetry-outputs-downloaded"
PHOTOGRAMMETRY_POSTPROCESSED_SUBDIR = "07_photogrammetry-outputs-postprocessed"

# The photogrammetry base config file in BASE_METASHAPE_CONFIG_SUBPATH should have the following ID
# as its filename (with a .yml extension)
PHOTOGRAMMETRY_CONFIG_ID = "02"

# The number of chunks to break the photogrammetry processing into (one chunk for each instance)
N_CHUNKS_PHOTOGRAMMETRY = 24



# For photogrammetry post-processing

# For COPC conversion, the current approach of using Untwine is super slow for large point clouds
# due to the extensive rapid file caching and the files being stored on the NFS server. Therefore we
# can use Metashape for the conversion and disable here.
CONVERT_TO_COPC = FALSE

# What fraction of the system RAM can TERRA use. The terra default is 0.6, you cannot go above 0.9
# without a warning.
TERRA_MEMFRAC = 0.9
OUTPUT_MAX_DIM = 800

TEMPDIR = file.path(BASE_DATA_PATH, "tmp/data-catalog-prep/")

## Some setup that should apply to any scripts we run

terra::terraOptions(memfrac = TERRA_MEMFRAC)

# Set the tempdir
unixtools::set.tempdir(TEMPDIR)
cat("Tempdir is:", tempdir(), "\n")


# For ITD

CHMS_FOR_ITD_LIST_PATH = file.path(BASE_DATA_PATH, "00_missions-to-process/04_itd/chms-for-itd.csv")

ITD_PARAMETERIZATION_ID = 1
CHM_RES = 0.25
CHM_SMOOTH_WIDTH = 7
LMF_A = 0
LMF_B = 0.11
LMF_C = 0
LMF_DIAM_MIN = 0.5
LMF_DIAM_MAX = 100

# The folder beneath the mission processed folder where the ITD outputs will be stored (in the
# Object Store))
ITD_FOLDER = paste0("itd_", str_pad(ITD_PARAMETERIZATION_ID, width = 4, pad = "0", side = "left"))




### Drone imagery web catalog

BASE_OFO_URL = "https://openforestobservatory.org/"
# BASE_OFO_URL = "http://localhost:1313/"
WEBSITE_REPO_PATH = "ofo-website-3"

# Path to the plot details template page within this repo
MISSION_DETAILS_TEMPLATE_FILEPATH = fs::path("deploy/drone-imagery-ingestion/10_drone-mission-web-catalog/templates/drone-mission-details.md")

# Path to plot details dir relative to the 'content' dir in the website repo. No leading slash but
# trailing slash
MISSION_DETAILS_PAGE_DIR = "data/drone/mission-details/"

# Path to static website files dirs within website repo relative to 'static'. Leading slash but no
# trailing slash
DATATABLE_HEADER_FILES_DIR = "/datatable-header-files_drone-mission-catalog"
LEAFLET_HEADER_FILES_DIR = "/leaflet-header-files_drone-mission-catalog"
MISSION_CATALOG_DATATABLE_DIR = "/drone-mission-catalog-datatable/"
MISSION_CATALOG_DATATABLE_FILENAME = "drone-mission-catalog-datatable.html"
MISSION_CATALOG_MAP_DIR = "/drone-mission-catalog-map/"
MISSION_CATALOG_MAP_FILENAME = "drone-mission-catalog-map.html"
MISSION_DETAILS_DATATABLE_DIR = "/drone-mission-details-datatables"
MISSION_DETAILS_MAP_DIR = "/drone-mission-details-maps"
ITD_MAP_DIR = "/itd-maps"

WEBSITE_STATIC_PATH = file.path(WEBSITE_REPO_PATH, "static", "")
WEBSITE_CONTENT_PATH = file.path(WEBSITE_REPO_PATH, "content", "")

DATA_SERVER_BASE_URL = "https://js2.jetstream-cloud.org:8001/swift/v1/"
DATA_SERVER_MISSIONS_BASE_URL = paste0(DATA_SERVER_BASE_URL, REMOTE_MISSIONS_DIR)

# Metadata pulled from S3 to use in catalog generation
MISSION_METADATA_FILEPATH = file.path(BASE_DATA_PATH, "05_drone-imagery-web-catalog/01_metadata/pre-curation/mission-metadata.gpkg")
IMAGE_METADATA_FILEPATH = file.path(BASE_DATA_PATH, "05_drone-imagery-web-catalog/01_metadata/pre-curation/image-metadata.gpkg")
S3_LISTING_FILEPATH = file.path(BASE_DATA_PATH, "05_drone-imagery-web-catalog/01_metadata/pre-curation/s3-listing.csv")

# Post-curation metadata pulled from staged location for web catalog generation
POST_CURATION_MISSION_METADATA_FILEPATH = file.path(BASE_DATA_PATH, "05_drone-imagery-web-catalog/01_metadata/post-curation/mission-metadata.gpkg")
POST_CURATION_IMAGE_METADATA_FILEPATH = file.path(BASE_DATA_PATH, "05_drone-imagery-web-catalog/01_metadata/post-curation/image-metadata.gpkg")

# Lists of mission and plot IDs to withhold from broad-scale ML training (save for testing)
MISSIONS_TO_WITHHOLD_FILEPATH = file.path(BASE_DATA_PATH, "stratification-data/strat-output/withheld_drone_mission_ids_v1.csv")

# For internal curation site generation
# Set both to empty strings ("") if not using secondary metadata/override functionality
SECONDARY_IMAGE_METADATA_FILEPATH = file.path(BASE_DATA_PATH, "05_drone-imagery-web-catalog/01_metadata/pre-curation/image-metadata_previous-curation-records_2025-04-19.gpkg")
IMAGERY_METADATA_MISSION_OVERRIDE_LIST_FILEPATH = file.path(BASE_DATA_PATH, "05_drone-imagery-web-catalog/01_metadata/pre-curation/previous-curation-records-metadata-mission-override-list_2025-04-19.csv")

CURATION_MISSION_DETAILS_TEMPLATE_FILEPATH = fs::path("deploy/drone-imagery-ingestion/10_drone-mission-web-catalog/templates/drone-mission-details_curation.md")
CURATION_MISSION_CATALOG_TEMPLATE_FILEPATH = fs::path("deploy/drone-imagery-ingestion/10_drone-mission-web-catalog/templates/drone-mission-catalog_curation.html")
CURATION_MISSION_DETAILS_PAGE_DIR = "data/drone-curation/mission-details/"
CURATION_DATATABLE_HEADER_FILES_DIR = "/datatable-header-files_drone-curation"
CURATION_LEAFLET_HEADER_FILES_DIR = "/leaflet-header-files_drone-curation"
CURATION_MISSION_CATALOG_DATATABLE_DIR = "/drone-curation-mission-catalog-datatable"
CURATION_MISSION_CATALOG_DATATABLE_FILENAME = "drone-curation-mission-catalog-datatable.html"
CURATION_MISSION_CATALOG_MAP_DIR = "/drone-curation-mission-catalog-map"
CURATION_MISSION_CATALOG_MAP_FILENAME = "drone-curation-mission-catalog-map.html"
CURATION_MISSION_DETAILS_DATATABLE_DIR = "/drone-curation-mission-details-datatables"
CURATION_MISSION_DETAILS_MAP_DIR = "/drone-curation-mission-details-maps"

# Post-curation widget output directories (for curation pages showing post-curation data)
CURATION_POST_MISSION_DETAILS_DATATABLE_DIR = "/drone-curation-post-mission-details-datatables"
CURATION_POST_MISSION_DETAILS_MAP_DIR = "/drone-curation-post-mission-details-maps"

# nolint end